export default [
    {
        "FInterID": 1,
        "FBillNO": "S11-BKAACSC00085-0625128038-9",
        "FDate": "2023-04-26 00:00:00",
        "HAWB": "BKAACSC00085",
        "FPalletSeq": 1,
        "FPalletCount": 1,
        "FGrossweight": 1,
        "FEmptyCarton": 1,
        "FUserID": 0,
        "FCreateDatetime": "2022-05-12 13:25:50",
        "FStatus": 1,
        "FShipNO": "1",
        "FCTN": 54,
        "FProjectNO": "1",
        "Region": "1",
        "Country": "US",
        "HubCode": "LO15",
        "TruckNo": "1",
        "ReferenceNO": "S14-LO15-20220318",
        "Carrier": "XFTNQ",
        "ShipID": "7096771461",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 300Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "1",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 1,
        "FKPONO": "0625128038",
        "FMPNNO": "MM213ZM/A",
        "FCTN2": 54,
        "FStatus2": 0,
        "FOutSN": 1,
        "FLineItem": "00060",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE MIDNIGHT-ZML",
        "FQTY": 540,
        "FCrossWeight": 79.92,
        "FNetWeight": 5.4,
        "FCarrierNo": "XFTNQ",
        "FCommercialInvoice": "LO15S14-20220518",
        "FProjectNO2": "S11"
    },
    {
        "FInterID": 2,
        "FBillNO": "BKKCOS000563-2-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000563",
        "FPalletSeq": 1,
        "FPalletCount": 1,
        "FGrossweight": 41,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 17:48:16",
        "FStatus": 0,
        "FShipNO": "1-RL04",
        "FCTN": 32,
        "FProjectNO": "S12",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL04",
        "TruckNo": "1",
        "ReferenceNO": null,
        "Carrier": "XAPXL",
        "ShipID": "7090191858",
        "ReturnAddress": "A.I. 100 QUALITY CIRCLE, SUITE 192 HARRISBURG, PA 17112 USA",
        "DeliveryToName": "A.I. RETAIL HUB EAST C/O Geodis",
        "AdditionalDeliveryToName": "951 Willowbrook RdNorthhampton, PA 18067-8801Northhampton",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000563",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "JFK",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 2,
        "FKPONO": "5700264032-1",
        "FMPNNO": "MM2A3ZM/A",
        "FCTN2": 16,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00030",
        "FPartNumberDesc": "IPHONE 13 SI CASE MIDNIGHT-ZML",
        "FQTY": 160,
        "FCrossWeight": 20.64,
        "FNetWeight": 1.6,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL04S12-20220221",
        "FProjectNO2": "S12"
    },
    {
        "FInterID": 2,
        "FBillNO": "BKKCOS000563-2-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000563",
        "FPalletSeq": 1,
        "FPalletCount": 1,
        "FGrossweight": 41,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 17:48:16",
        "FStatus": 0,
        "FShipNO": "1-RL04",
        "FCTN": 32,
        "FProjectNO": "S12",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL04",
        "TruckNo": "1",
        "ReferenceNO": null,
        "Carrier": "XAPXL",
        "ShipID": "7090191858",
        "ReturnAddress": "A.I. 100 QUALITY CIRCLE, SUITE 192 HARRISBURG, PA 17112 USA",
        "DeliveryToName": "A.I. RETAIL HUB EAST C/O Geodis",
        "AdditionalDeliveryToName": "951 Willowbrook RdNorthhampton, PA 18067-8801Northhampton",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000563",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "JFK",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 2,
        "FDetailID": 3,
        "FKPONO": "5700264032-2",
        "FMPNNO": "MM2A3ZM/A",
        "FCTN2": 16,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00030",
        "FPartNumberDesc": "IPHONE 13 SI CASE MIDNIGHT-ZML",
        "FQTY": 160,
        "FCrossWeight": 20.64,
        "FNetWeight": 1.6,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL04S12-20220221",
        "FProjectNO2": "S12"
    },
    {
        "FInterID": 3,
        "FBillNO": "BKKCOS000562-2-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000562",
        "FPalletSeq": 1,
        "FPalletCount": 2,
        "FGrossweight": 185,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL01",
        "FCTN": 144,
        "FProjectNO": "S12",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL01",
        "TruckNo": "1",
        "ReferenceNO": null,
        "Carrier": "XAPXL",
        "ShipID": "7090190943",
        "ReturnAddress": "A.I. 558 ALDI BLVD. MT. JULIET, TN 37122 USA",
        "DeliveryToName": "A.I. RETAIL Hub Center C/OO Geodis",
        "AdditionalDeliveryToName": "1000 Darrell Waltrip Dr,Lebanon, TN, 37090Lebanon",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000562",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "ORD",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 4,
        "FKPONO": "5700273755-1",
        "FMPNNO": "MM2A3ZM/A",
        "FCTN2": 80,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00030",
        "FPartNumberDesc": "IPHONE 13 SI CASE MIDNIGHT-ZML",
        "FQTY": 800,
        "FCrossWeight": 103.2,
        "FNetWeight": 8,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL01S12-20220221",
        "FProjectNO2": "S12"
    },
    {
        "FInterID": 3,
        "FBillNO": "BKKCOS000562-2-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000562",
        "FPalletSeq": 1,
        "FPalletCount": 2,
        "FGrossweight": 185,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL01",
        "FCTN": 144,
        "FProjectNO": "S12",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL01",
        "TruckNo": "1",
        "ReferenceNO": null,
        "Carrier": "XAPXL",
        "ShipID": "7090190943",
        "ReturnAddress": "A.I. 558 ALDI BLVD. MT. JULIET, TN 37122 USA",
        "DeliveryToName": "A.I. RETAIL Hub Center C/OO Geodis",
        "AdditionalDeliveryToName": "1000 Darrell Waltrip Dr,Lebanon, TN, 37090Lebanon",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000562",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "ORD",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 2,
        "FDetailID": 5,
        "FKPONO": "5700273755-2",
        "FMPNNO": "MM2A3ZM/A",
        "FCTN2": 64,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00030",
        "FPartNumberDesc": "IPHONE 13 SI CASE MIDNIGHT-ZML",
        "FQTY": 640,
        "FCrossWeight": 82.56,
        "FNetWeight": 6.4,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL01S12-20220221",
        "FProjectNO2": "S12"
    },
    {
        "FInterID": 4,
        "FBillNO": "BKKCOS000562-2-2",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000562",
        "FPalletSeq": 2,
        "FPalletCount": 2,
        "FGrossweight": 20,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL01",
        "FCTN": 16,
        "FProjectNO": "S12",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL01",
        "TruckNo": "1",
        "ReferenceNO": null,
        "Carrier": "XAPXL",
        "ShipID": "7090190943",
        "ReturnAddress": "A.I. 558 ALDI BLVD. MT. JULIET, TN 37122 USA",
        "DeliveryToName": "A.I. RETAIL Hub Center C/OO Geodis",
        "AdditionalDeliveryToName": "1000 Darrell Waltrip Dr,Lebanon, TN, 37090Lebanon",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000562",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "ORD",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 6,
        "FKPONO": "5700273755-2",
        "FMPNNO": "MM2A3ZM/A",
        "FCTN2": 16,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00030",
        "FPartNumberDesc": "IPHONE 13 SI CASE MIDNIGHT-ZML",
        "FQTY": 160,
        "FCrossWeight": 20.64,
        "FNetWeight": 1.6,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL01S12-20220221",
        "FProjectNO2": "S12"
    },
    {
        "FInterID": 5,
        "FBillNO": "S14-BKKCOS000589-5700249586-1-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 1,
        "FPalletCount": 3,
        "FGrossweight": 189,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 128,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 7,
        "FKPONO": "5700249586-1",
        "FMPNNO": "MM2T3ZM/A",
        "FCTN2": 128,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00060",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE ABYSS BLUE-ZML",
        "FQTY": 1280,
        "FCrossWeight": 189.44,
        "FNetWeight": 12.8,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 6,
        "FBillNO": "S14-BKKCOS000589-5700249586-1-2",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 2,
        "FPalletCount": 3,
        "FGrossweight": 189,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 128,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 8,
        "FKPONO": "5700249586-1",
        "FMPNNO": "MM2T3ZM/A",
        "FCTN2": 128,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00060",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE ABYSS BLUE-ZML",
        "FQTY": 1280,
        "FCrossWeight": 189.44,
        "FNetWeight": 12.8,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 7,
        "FBillNO": "S14-BKKCOS000589-5700249586-1-3",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 3,
        "FPalletCount": 3,
        "FGrossweight": 90,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 61,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 9,
        "FKPONO": "5700249586-1",
        "FMPNNO": "MM2T3ZM/A",
        "FCTN2": 61,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00060",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE ABYSS BLUE-ZML",
        "FQTY": 610,
        "FCrossWeight": 90.28,
        "FNetWeight": 6.1,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 8,
        "FBillNO": "S14-BKKCOS000589-5700249586-2-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 1,
        "FPalletCount": 2,
        "FGrossweight": 189,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 128,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 10,
        "FKPONO": "5700249586-2",
        "FMPNNO": "MM2U3ZM/A",
        "FCTN2": 128,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00070",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE MIDNIGHT-ZML",
        "FQTY": 1280,
        "FCrossWeight": 189.44,
        "FNetWeight": 12.8,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 9,
        "FBillNO": "S14-BKKCOS000589-5700249586-2-2",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 2,
        "FPalletCount": 2,
        "FGrossweight": 32,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 22,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 11,
        "FKPONO": "5700249586-2",
        "FMPNNO": "MM2U3ZM/A",
        "FCTN2": 22,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00070",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE MIDNIGHT-ZML",
        "FQTY": 220,
        "FCrossWeight": 32.56,
        "FNetWeight": 2.2,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 10,
        "FBillNO": "S14-BKKCOS000589-5700249586-3-1",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "BKKCOS000589",
        "FPalletSeq": 1,
        "FPalletCount": 1,
        "FGrossweight": 59,
        "FEmptyCarton": 0,
        "FUserID": 0,
        "FCreateDatetime": "2023-03-15 18:02:17",
        "FStatus": 0,
        "FShipNO": "1-RL05",
        "FCTN": 40,
        "FProjectNO": "S14",
        "Region": "AMR",
        "Country": "US",
        "HubCode": "RL05",
        "TruckNo": "1",
        "ReferenceNO": "S14-RL05-20220225",
        "Carrier": "XAPXL",
        "ShipID": "7091386827",
        "ReturnAddress": "A.I. 1710 W BASELINE AVE, SUITE 100 RIALTO, CA 92376 USA",
        "DeliveryToName": "A.I. RETAIL HUB WEST DC C/O Geodis",
        "AdditionalDeliveryToName": "1710 W Base Line Rd Suite 500Rialto, CA 92376Rialto",
        "DeliveryStreetAddress": "d",
        "DeliveryCityName": "d2",
        "DeliveryPostalCode": "d3",
        "DeliveryRegion": "d4",
        "DeliveryCountry": "US",
        "TelNo": "t",
        "MAWB_OceanContainerNumber": "BKKCOS000589",
        "TotalVolume": "0",
        "VolumeUnit": "v",
        "TransportMethod": "00",
        "Origin": "BKK",
        "POE_COC": "POE",
        "POE": "LAX",
        "PalletSN": "p",
        "CTRY": "C",
        "SHA": "S",
        "Sales": "sa",
        "WebJ": null,
        "UUI": "uui",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "sp",
        "SCAC": "scac",
        "OEMSpecificPO1": "po1",
        "OEMSpecificPO2": "po2",
        "FEntryID": 1,
        "FDetailID": 12,
        "FKPONO": "5700249586-3",
        "FMPNNO": "MM2V3ZM/A",
        "FCTN2": 40,
        "FStatus2": 0,
        "FOutSN": 0,
        "FLineItem": "00080",
        "FPartNumberDesc": "IPHONE 13 PRO MAX SI CASE RED-ZML",
        "FQTY": 400,
        "FCrossWeight": 59.2,
        "FNetWeight": 4,
        "FCarrierNo": "XAPXL",
        "FCommercialInvoice": "RL05S14-20220225",
        "FProjectNO2": "S14"
    },
    {
        "FInterID": 15,
        "FBillNO": "1111111-2",
        "FDate": "2023-04-21 10:00:00",
        "HAWB": "1111111",
        "FPalletSeq": 0,
        "FPalletCount": 0,
        "FGrossweight": 0,
        "FEmptyCarton": 0,
        "FUserID": null,
        "FCreateDatetime": null,
        "FStatus": 0,
        "FShipNO": "",
        "FCTN": null,
        "FProjectNO": "",
        "Region": "",
        "Country": "2",
        "HubCode": "2",
        "TruckNo": "2",
        "ReferenceNO": "2",
        "Carrier": "2",
        "ShipID": "2",
        "ReturnAddress": "2",
        "DeliveryToName": "2",
        "AdditionalDeliveryToName": "2",
        "DeliveryStreetAddress": "2",
        "DeliveryCityName": "2",
        "DeliveryPostalCode": "2",
        "DeliveryRegion": "2",
        "DeliveryCountry": "2",
        "TelNo": "2",
        "MAWB_OceanContainerNumber": "",
        "TotalVolume": "2",
        "VolumeUnit": null,
        "TransportMethod": "2",
        "Origin": "2",
        "POE_COC": "2",
        "POE": "2",
        "PalletSN": "2",
        "CTRY": "",
        "SHA": "",
        "Sales": "",
        "WebJ": null,
        "UUI": "",
        "DNJ": null,
        "DeliveryJ": null,
        "Special": "",
        "SCAC": "",
        "OEMSpecificPO1": "",
        "OEMSpecificPO2": "",
        "FEntryID": 1,
        "FDetailID": 13,
        "FKPONO": "1",
        "FMPNNO": "1",
        "FCTN2": 1,
        "FStatus2": 0,
        "FOutSN": null,
        "FLineItem": "1",
        "FPartNumberDesc": "1",
        "FQTY": 1,
        "FCrossWeight": 1,
        "FNetWeight": 1,
        "FCarrierNo": "1",
        "FCommercialInvoice": "1",
        "FProjectNO2": "S12"
    }
]