export default /* [
  { key: 0, name: "Ban Ki-moon 반기문", nation: "SouthKorea", title: "Secretary-General of the United Nations", headOf: "Secretariat" },
  { key: 1, boss: 0, name: "Patricia O'Brien", nation: "Ireland", title: "Under-Secretary-General for Legal Affairs and United Nations Legal Counsel", headOf: "Office of Legal Affairs" },
  { key: 3, boss: 1, name: "Peter Taksøe-Jensen", nation: "Denmark", title: "Assistant Secretary-General for Legal Affairs" },
  { key: 9, boss: 3, name: "Other Employees" },
  { key: 4, boss: 1, name: "Maria R. Vicien - Milburn", nation: "Argentina", title: "General Legal Division Director", headOf: "General Legal Division" },
  { key: 10, boss: 4, name: "Other Employees" },
  { key: 5, boss: 1, name: "Václav Mikulka", nation: "CzechRepublic", title: "Codification Division Director", headOf: "Codification Division" },
  { key: 11, boss: 5, name: "Other Employees" },
  { key: 6, boss: 1, name: "Sergei Tarassenko", nation: "Russia", title: "Division for Ocean Affairs and the Law of the Sea Director", headOf: "Division for Ocean Affairs and the Law of the Sea" },
  { key: 12, boss: 6, name: "Alexandre Tagore Medeiros de Albuquerque", nation: "Brazil", title: "Chairman of the Commission on the Limits of the Continental Shelf", headOf: "The Commission on the Limits of the Continental Shelf" },
  { key: 17, boss: 12, name: "Peter F. Croker", nation: "Ireland", title: "Chairman of the Committee on Confidentiality", headOf: "The Committee on Confidentiality" },
  { key: 31, boss: 17, name: "Michael Anselme Marc Rosette", nation: "Seychelles", title: "Vice Chairman of the Committee on Confidentiality" },
  { key: 32, boss: 17, name: "Kensaku Tamaki", nation: "Japan", title: "Vice Chairman of the Committee on Confidentiality" },
  { key: 33, boss: 17, name: "Osvaldo Pedro Astiz", nation: "Argentina", title: "Member of the Committee on Confidentiality" },
  { key: 34, boss: 17, name: "Yuri Borisovitch Kazmin", nation: "Russia", title: "Member of the Committee on Confidentiality" },
  { key: 18, boss: 12, name: "Philip Alexander Symonds", nation: "Australia", title: "Chairman of the Committee on provision of scientific and technical advice to coastal States", headOf: "Committee on provision of scientific and technical advice to coastal States" },
  { key: 35, boss: 18, name: "Emmanuel Kalngui", nation: "Cameroon", title: "Vice Chairman of the Committee on provision of scientific and technical advice to coastal States" },
  { key: 36, boss: 18, name: "Sivaramakrishnan Rajan", nation: "India", title: "Vice Chairman of the Committee on provision of scientific and technical advice to coastal States" },
  { key: 37, boss: 18, name: "Francis L. Charles", nation: "TrinidadAndTobago", title: "Member of the Committee on provision of scientific and technical advice to costal States" },
  { key: 38, boss: 18, name: "Mihai Silviu German", nation: "Romania", title: "Member of the Committee on provision of scientific and technical advice to costal States" },
  { key: 19, boss: 12, name: "Lawrence Folajimi Awosika", nation: "Nigeria", title: "Vice Chairman of the Commission on the Limits of the Continental Shelf" },
  { key: 20, boss: 12, name: "Harald Brekke", nation: "Norway", title: "Vice Chairman of the Commission on the Limits of the Continental Shelf" },
  { key: 21, boss: 12, name: "Yong-Ahn Park", nation: "SouthKorea", title: "Vice Chairman of the Commission on the Limits of the Continental Shelf" },
  { key: 22, boss: 12, name: "Abu Bakar Jaafar", nation: "Malaysia", title: "Chairman of the Editorial Committee", headOf: "Editorial Committee" },
  { key: 23, boss: 12, name: "Galo Carrera Hurtado", nation: "Mexico", title: "Chairman of the Training Committee", headOf: "Training Committee" },
  { key: 24, boss: 12, name: "Indurlall Fagoonee", nation: "Mauritius", title: "Member of the Commission on the Limits of the Continental Shelf" },
  { key: 25, boss: 12, name: "George Jaoshvili", nation: "Georgia", title: "Member of the Commission on the Limits of the Continental Shelf" },
  { key: 26, boss: 12, name: "Wenzhang Lu", nation: "China", title: "Member of the Commission on the Limits of the Continental Shelf" },
  { key: 27, boss: 12, name: "Isaac Owusu Orudo", nation: "Ghana", title: "Member of the Commission on the Limits of the Continental Shelf" },
  { key: 28, boss: 12, name: "Fernando Manuel Maia Pimentel", nation: "Portugal", title: "Member of the Commission on the Limits of the Continental Shelf" },
  { key: 7, boss: 1, name: "Renaud Sorieul", nation: "France", title: "International Trade Law Division Director", headOf: "International Trade Law Division" },
  { key: 13, boss: 7, name: "Other Employees" },
  { key: 8, boss: 1, name: "Annebeth Rosenboom", nation: "Netherlands", title: "Treaty Section Chief", headOf: "Treaty Section" },
  { key: 14, boss: 8, name: "Bradford Smith", nation: "UnitedStates", title: "Substantive Legal Issues Head", headOf: "Substantive Legal Issues" },
  { key: 29, boss: 14, name: "Other Employees" },
  { key: 15, boss: 8, name: "Andrei Kolomoets", nation: "Russia", title: "Technical/Legal Issues Head", headOf: "Technical/Legal Issues" },
  { key: 30, boss: 15, name: "Other Employees" },
  { key: 16, boss: 8, name: "Other Employees" },
  { key: 2, boss: 0, name: "Heads of Other Offices/Departments" }
]
 */
  /*
    {
      "class": "TreeModel",
      "nodeDataArray": [
        { "key": 1, "name": "Stella Payne Diaz", "title": "CEO", "pic": "1.jpg" },
        { "key": 2, "name": "Luke Warm", "title": "VP Marketing/Sales", "pic": "2.jpg", "parent": 1 },
        { "key": 3, "name": "Meg Meehan Hoffa", "title": "Sales", "pic": "3.jpg", "parent": 2 },
        { "key": 4, "name": "Peggy Flaming", "title": "VP Engineering", "pic": "4.jpg", "parent": 1 },
        { "key": 5, "name": "Saul Wellingood", "title": "Manufacturing", "pic": "5.jpg", "parent": 4 },
        { "key": 6, "name": "Al Ligori", "title": "Marketing", "pic": "6.jpg", "parent": 2 },
        { "key": 7, "name": "Dot Stubadd", "title": "Sales Rep", "pic": "7.jpg", "parent": 3 },
        { "key": 8, "name": "Les Ismore", "title": "Project Mgr", "pic": "8.jpg", "parent": 5 },
        { "key": 9, "name": "April Lynn Parris", "title": "Events Mgr", "pic": "9.jpg", "parent": 6 },
        { "key": 10, "name": "Xavier Breath", "title": "Engineering", "pic": "10.jpg", "parent": 4 },
        { "key": 11, "name": "Anita Hammer", "title": "Process", "pic": "11.jpg", "parent": 5 },
        { "key": 12, "name": "Billy Aiken", "title": "Software", "pic": "12.jpg", "parent": 10 },
        { "key": 13, "name": "Stan Wellback", "title": "Testing", "pic": "13.jpg", "parent": 10 },
        { "key": 14, "name": "Marge Innovera", "title": "Hardware", "pic": "14.jpg", "parent": 10 },
        { "key": 15, "name": "Evan Elpus", "title": "Quality", "pic": "15.jpg", "parent": 5 },
        { "key": 16, "name": "Lotta B. Essen", "title": "Sales Rep", "pic": "16.jpg", "parent": 3 },
        { "name": "Jason", "title": "\u8f6f\u4ef6\u5de5\u7a0b\u5e08", "comments": "", "parent": 1, "key": 29, "pic": "upload/20231201/20231201162235976412862.png" },
        { "name": "\u6d0b\u8471", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 17, "pic": "upload/20231201/20231201162751252172510.jpg" },
        { "name": "\u571f\u8c46", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 18, "pic": "upload/20231201/20231201162854958288331.jpg" },
        { "name": "\u60a0\u60a0", "title": "\u6587\u5458", "comments": "", "parent": 29, "key": 19, "pic": "upload/20231201/20231201163057806068003.jpg" },
        { "name": "\u8001\u9e70", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 20, "pic": "upload/20231201/20231201163007318877875.ico" }
      ]
    } */
  /*
    {
      "class": "TreeModel",
      "nodeDataArray": [
        { "key": 1, "name": "Stella Payne Diaz", "title": "CEO", "pic": "upload/20231213/20231213135554491561788.png" },
        { "key": 2, "name": "Luke Warm", "title": "VP Marketing/Sales", "pic": "", "parent": 1 },
        { "key": 3, "name": "Meg Meehan Hoffa", "title": "Sales", "pic": "", "parent": 2 },
        { "key": 4, "name": "Peggy Flaming", "title": "VP Engineering", "pic": "", "parent": 1 },
        { "key": 5, "name": "Saul Wellingood", "title": "Manufacturing", "pic": "", "parent": 4 },
        { "key": 6, "name": "Al Ligori", "title": "Marketing", "pic": "", "parent": 2 },
        { "key": 7, "name": "Dot Stubadd", "title": "Sales Rep", "pic": "", "parent": 3 },
        { "key": 8, "name": "Les Ismore", "title": "Project Mgr", "pic": "", "parent": 5 },
        { "key": 9, "name": "April Lynn Parris", "title": "Events Mgr", "pic": "", "parent": 6 },
        { "key": 10, "name": "Xavier Breath", "title": "Engineering", "pic": "", "parent": 4 },
        { "key": 11, "name": "Anita Hammer", "title": "Process", "pic": "", "parent": 5 },
        { "key": 12, "name": "Billy Aiken", "title": "Software", "pic": "", "parent": 10 },
        { "key": 13, "name": "Stan Wellback", "title": "Testing", "pic": "", "parent": 10 },
        { "key": 14, "name": "Marge Innovera", "title": "Hardware", "pic": "", "parent": 10 },
        { "key": 15, "name": "Evan Elpus", "title": "Quality", "pic": "", "parent": 5 },
        { "key": 16, "name": "Lotta B. Essen", "title": "Sales Rep", "pic": "", "parent": 3 },
        { "name": "Jason", "title": "\u8f6f\u4ef6\u5de5\u7a0b\u5e08", "comments": "", "parent": 1, "key": 29, "pic": "upload/20231201/20231201162235976412862.png" },
        { "name": "\u6d0b\u8471", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 17, "pic": "upload/20231201/20231201162751252172510.jpg" },
        { "name": "\u571f\u8c46", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 18, "pic": "upload/20231201/20231201162854958288331.jpg" },
        { "name": "\u60a0\u60a0", "title": "\u6587\u5458", "comments": "", "parent": 29, "key": 19, "pic": "upload/20231201/20231201163057806068003.jpg" },
        { "name": "\u8001\u9e70", "title": "\u5de5\u4eba", "comments": "", "parent": 29, "key": 20, "pic": "upload/20231201/20231201163007318877875.ico" }
      ]
    } */
  {
    "class": "TreeModel",
    "nodeDataArray": [
      { "key": 1, "name": "Salvatore Serio", "title": "CEO", "pic": "upload/20231213/20231213135554491561788.png" },
      { "key": 4, "name": "Lennon Cheng", "title": "IT Manager", "pic": "", "parent": 1 },
      { "key": 5, "name": "Dean He", "title": "IT Support Team Leader", "pic": "", "parent": 4 },
      { "name": "Vincent Wang", "title": "SFC Manager", "comments": "", "parent": 1, "key": 29, "pic": "upload/20231201/20231201162235976412862.png" },
      { "name": "Jason Zou", "title": "Software Engineer", "comments": "", "parent": 29, "key": 17, "pic": "upload/20231201/20231201162751252172510.jpg" },
      { "name": "Howard Liu", "title": "Software Engineer", "comments": "", "parent": 29, "key": 18, "pic": "upload/20231201/20231201162854958288331.jpg" },
      { "name": "Tony Zhang", "title": "Software Engineer", "comments": "", "parent": 29, "key": 19, "pic": "upload/20231201/20231201163057806068003.jpg" },
      { "name": "Carl Dong", "title": "SFC Engineer", "comments": "", "parent": 29, "key": 20, "pic": "upload/20231201/20231201163007318877875.ico" },
      { "name": "Taiping Jin", "title": "SFC Engineer", "comments": "", "parent": 29, "key": 7 },
      { "name": "Bright Yan", "title": "SFC Engineer", "comments": "", "parent": 29, "key": 8 },
      { "name": "Figo Tang", "title": "IT Support Engineer", "comments": "", "parent": 5, "key": 10 },
      { "name": "Leo Zhong", "title": "IT Support Engineer", "comments": "", "parent": 5, "key": 11 },
      { "name": "Duke Du", "title": "IT Support Engineer", "comments": "", "parent": 5, "key": 12 }
    ]
  }
